"""Drift detection between deployed (~/.claude) and source repo files.

Compares deployed files against the source repository to identify
files that have been modified in-place without being synced back.

Uses a deployment manifest (generated by deploy.ps1) to map deployed
paths back to their source paths. Falls back to legacy directory
mappings if no manifest is found.
"""

import hashlib
import json
import os
import time
from pathlib import Path
from typing import Dict, List, Optional


# Legacy fallback: directories to compare when no manifest exists
# (deployed path relative to ~/.claude -> source path relative to repo root)
LEGACY_DIR_MAPPINGS = [
    ('hooks', 'hooks'),
    ('docs', 'docs'),
    ('skills', 'skills'),
]

# Files to always skip (e.g. generated files that shouldn't be reverse-synced)
EXCLUDE_FILES = {'CLAUDE.md'}

# Patterns to exclude from comparison
EXCLUDE_DIRS = {'.obi', 'projects', '__pycache__', '.pytest_cache', 'node_modules', '.git'}
EXCLUDE_EXTENSIONS = {'.pyc', '.pyo', '.exe', '.dll'}

# Top-level deployed dirs scanned for unmanifested files. skills/ is multi-tenant
# (only walked under subdirs that already have ≥1 manifest entry, so externally
# managed skills like coordinator-healthcheck are skipped). hooks/ and docs/ are
# wholesale Obi-managed, so any file there without a manifest entry is orphan
# state. commands/ and agents/ are deliberately omitted: they may legitimately
# hold user-authored items alongside Obi-managed ones.
UNMANIFESTED_SCAN_DIRS = ('hooks', 'docs')
UNMANIFESTED_SCAN_MULTI_TENANT_DIRS = ('skills',)


# Re-exported from paths.py; preserves the 7 mock-seam patches in
# test_drift_detector.py that target 'core.drift_detector.get_source_repo_path'.
from .paths import get_obi_root, get_source_repo_path  # noqa: F401


def get_deployed_root() -> str:
    """Get the deployed Obi root for the active platform."""
    return str(get_obi_root())


def file_hash(
    path: str,
    deadline_monotonic: Optional[float] = None,
) -> Optional[str]:
    """Compute SHA256 hash of a file's content, normalizing line endings.

    Normalizes CRLF to LF before hashing so Windows vs Unix line endings
    don't register as drift.

    Returns None if the file doesn't exist or can't be read.
    """
    try:
        h = hashlib.sha256()
        pending = b''
        with open(path, 'rb') as f:
            while True:
                if _deadline_expired(deadline_monotonic):
                    return None
                chunk = f.read(1024 * 1024)
                if not chunk:
                    if pending:
                        h.update(pending)
                    break
                content = pending + chunk
                if content.endswith(b'\r'):
                    content, pending = content[:-1], b'\r'
                else:
                    pending = b''
                h.update(content.replace(b'\r\n', b'\n'))
        return h.hexdigest()
    except (OSError, IOError):
        return None


def _should_skip(path: str) -> bool:
    """Check if a path should be excluded from comparison."""
    basename = os.path.basename(path)
    if basename in EXCLUDE_FILES:
        return True
    parts = Path(path).parts
    for part in parts:
        if part in EXCLUDE_DIRS:
            return True
    _, ext = os.path.splitext(path)
    if ext.lower() in EXCLUDE_EXTENSIONS:
        return True
    return False


def load_manifest() -> Optional[Dict[str, str]]:
    """Load deployment manifest from ~/.claude/.obi/deployment-manifest.json.

    The manifest is generated by deploy.ps1 and maps deployed relative
    paths to their source relative paths.

    Returns:
        Dict mapping deployed relative paths to source relative paths,
        or None if manifest doesn't exist or is invalid.
    """
    manifest_path = os.path.join(get_deployed_root(), '.obi', 'deployment-manifest.json')
    try:
        # utf-8-sig handles optional BOM from PowerShell 5.1
        with open(manifest_path, 'r', encoding='utf-8-sig') as f:
            data = json.load(f)
        mappings = data.get('mappings')
        if isinstance(mappings, dict) and len(mappings) > 0:
            return mappings
        return None
    except (OSError, IOError, json.JSONDecodeError, ValueError):
        return None


def get_file_pairs() -> List[Dict]:
    """Build list of deployed-to-source file pairs for comparison.

    Uses the deployment manifest when available (accurate for all paths
    including flattened commands/ and agents/). Falls back to legacy
    directory mappings if no manifest exists.

    Returns list of dicts with keys:
        - deployed: absolute path to deployed file
        - source: absolute path to source file
        - relative: relative path for display (e.g. commands/obi.md)
    """
    source_root = get_source_repo_path()
    if source_root is None:
        return []

    deployed_root = get_deployed_root()
    pairs = []

    # Try manifest first (generated by deploy.ps1)
    manifest = load_manifest()
    if manifest:
        for deployed_rel, source_rel in manifest.items():
            if _should_skip(deployed_rel):
                continue

            deployed_path = deployed_rel.replace('/', os.sep)
            if os.path.isabs(deployed_path):
                deployed_abs = deployed_path
            else:
                deployed_abs = os.path.join(deployed_root, deployed_path)
            source_abs = os.path.join(source_root, source_rel.replace('/', os.sep))

            if os.path.isfile(deployed_abs):
                pairs.append({
                    'deployed': deployed_abs,
                    'source': source_abs,
                    'relative': deployed_rel,
                })
        return pairs

    # Legacy fallback: walk directories with 1:1 path mapping
    # Only covers hooks, docs, skills (commands/agents have no 1:1 source dir)
    for deployed_dir, source_dir in LEGACY_DIR_MAPPINGS:
        deployed_abs = os.path.join(deployed_root, deployed_dir)
        source_abs = os.path.join(source_root, source_dir)

        if not os.path.isdir(deployed_abs):
            continue

        for root, dirs, files in os.walk(deployed_abs):
            dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS]

            for fname in files:
                deployed_file = os.path.join(root, fname)
                rel = os.path.relpath(deployed_file, deployed_abs)

                if _should_skip(rel):
                    continue

                source_file = os.path.join(source_abs, rel)
                display_rel = os.path.join(deployed_dir, rel).replace('\\', '/')

                pairs.append({
                    'deployed': deployed_file,
                    'source': source_file,
                    'relative': display_rel,
                })

    # Settings.json special case (legacy only; manifest includes it)
    username = os.environ.get('USERNAME') or os.environ.get('USER', '')
    if username:
        settings_deployed = os.path.join(deployed_root, 'settings.json')
        settings_source = os.path.join(source_root, 'users', username, 'settings.json')
        if os.path.isfile(settings_deployed):
            pairs.append({
                'deployed': settings_deployed,
                'source': settings_source,
                'relative': 'settings.json',
            })

    return pairs


def _deadline_expired(deadline_monotonic: Optional[float]) -> bool:
    return deadline_monotonic is not None and time.monotonic() >= deadline_monotonic


def detect_unmanifested(
    manifest: Optional[Dict[str, str]],
    deployed_root: str,
    deadline_monotonic: Optional[float] = None,
) -> List[Dict]:
    """Find files in Obi-managed deployed dirs that aren't in the manifest.

    Closes the blind spot where a deployed-only file (created locally without
    a source counterpart) never surfaces because detect_drift() walks the
    manifest, not the deployed tree.

    Skips externally managed multi-tenant subdirs (e.g. skills/coordinator-
    healthcheck/ which has zero manifest entries). Only scans dirs listed in
    UNMANIFESTED_SCAN_DIRS and UNMANIFESTED_SCAN_MULTI_TENANT_DIRS — commands/
    and agents/ are excluded because they may legitimately hold user-authored
    items.
    """
    if not manifest:
        return []

    manifest_paths = set(manifest.keys())
    unmanifested: List[Dict] = []

    def walk_dir(top_rel: str, multi_tenant: bool) -> None:
        top_abs = os.path.join(deployed_root, top_rel)
        if not os.path.isdir(top_abs):
            return
        for root, dirs, files in os.walk(top_abs):
            if _deadline_expired(deadline_monotonic):
                return
            dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS]
            for fname in files:
                if _deadline_expired(deadline_monotonic):
                    return
                file_abs = os.path.join(root, fname)
                rel = os.path.relpath(file_abs, deployed_root).replace('\\', '/')
                if _should_skip(rel) or rel in manifest_paths:
                    continue
                if multi_tenant:
                    parts = rel.split('/')
                    if len(parts) >= 2:
                        subdir_prefix = f'{parts[0]}/{parts[1]}/'
                        if not any(p.startswith(subdir_prefix) for p in manifest_paths):
                            continue
                unmanifested.append({
                    'deployed': file_abs,
                    'source': None,
                    'relative': rel,
                    'status': 'unmanifested',
                })

    for d in UNMANIFESTED_SCAN_DIRS:
        walk_dir(d, multi_tenant=False)
    for d in UNMANIFESTED_SCAN_MULTI_TENANT_DIRS:
        walk_dir(d, multi_tenant=True)

    return unmanifested


def detect_drift(deadline_monotonic: Optional[float] = None) -> Dict:
    """Compare all deployed files against their source counterparts.

    Returns dict with:
        - drifted: list of drifted file dicts
        - checked: number of file pairs checked
        - source_path: path to source repo (or None)
        - total_drifted: count of drifted files
    """
    source_path = get_source_repo_path()
    result = {
        'drifted': [],
        'checked': 0,
        'source_path': source_path,
        'total_drifted': 0,
        'timed_out': False,
    }

    if source_path is None:
        return result

    pairs = get_file_pairs()
    result['checked'] = len(pairs)

    for pair in pairs:
        if _deadline_expired(deadline_monotonic):
            result['timed_out'] = True
            break
        deployed_hash = file_hash(pair['deployed'], deadline_monotonic)
        if _deadline_expired(deadline_monotonic):
            result['timed_out'] = True
            break
        source_hash = file_hash(pair['source'], deadline_monotonic)
        if _deadline_expired(deadline_monotonic):
            result['timed_out'] = True
            break

        if deployed_hash is None:
            # Deployed file disappeared (shouldn't happen since we walked it)
            continue

        if source_hash is None:
            # Source file doesn't exist — deployed-only file
            result['drifted'].append({
                'deployed': pair['deployed'],
                'source': pair['source'],
                'relative': pair['relative'],
                'status': 'source_missing',
            })
        elif deployed_hash != source_hash:
            # Files differ
            result['drifted'].append({
                'deployed': pair['deployed'],
                'source': pair['source'],
                'relative': pair['relative'],
                'status': 'modified',
            })

    # Second pass: deployed files in Obi-managed dirs not in the manifest.
    if not result['timed_out']:
        result['drifted'].extend(
            detect_unmanifested(
                load_manifest(),
                get_deployed_root(),
                deadline_monotonic=deadline_monotonic,
            )
        )
        if _deadline_expired(deadline_monotonic):
            result['timed_out'] = True

    result['total_drifted'] = len(result['drifted'])
    return result


def format_drift_summary(drift_data: Dict) -> str:
    """Format drift detection results as a human-readable table.

    Args:
        drift_data: Output from detect_drift()

    Returns:
        Formatted string with drift summary.
    """
    if drift_data.get('source_path') is None:
        return "[Drift] Source repo not found. Set OBIWAG_SOURCE or clone to ~/source/obiwag-agents."

    checked = drift_data.get('checked', 0)
    drifted = drift_data.get('drifted', [])

    if not drifted:
        return f"[Drift] All {checked} files in sync."

    lines = [
        f"[Drift] {len(drifted)} of {checked} files differ from source repo:",
        "",
        "| Status | File |",
        "|--------|------|",
    ]

    for item in drifted:
        status_icon = {
            'modified': 'Modified',
            'source_missing': 'Deployed only',
            'deployed_missing': 'Source only',
            'unmanifested': 'Unmanifested',
        }.get(item['status'], item['status'])
        lines.append(f"| {status_icon} | `{item['relative']}` |")

    lines.append("")
    lines.append("Run `/obi-collect` to review and sync changes back to source.")

    return "\n".join(lines)
