"""User-prompt grounding with bounded reads and per-session deduplication."""

import re
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))


# Machine-generated envelopes that arrive through this hook, matched by their
# specific opening tag rather than by a bare leading "<". The distinction that
# matters is naming the known tags: a prompt merely starting with SOME tag is
# usually a user pasting XML, HTML, a manifest or a log — exactly the
# infrastructure-flavoured text most likely to mention PowerShell or GitHub.
_MACHINE_PREFIXES = (
    '<task-notification>',
    '<system-reminder>',
    '<local-command-stdout>',
    '<local-command-stderr>',
    '<command-message>',
    '<command-name>',
)

# Claude Code's compaction envelope. It summarizes everything touched all
# session, so it matches many patterns at once and describes the PAST task — it
# must not ground, and must not burn the once-per-topic budget.
_CONTINUATION_RE = re.compile(
    r'^\s*this session is being continued from a previous conversation',
    re.IGNORECASE,
)

_GROUNDING_SOFT_BUDGET_SEC = 7.0


def classify_prompt(prompt: str) -> str:
    """Return ``'user'``, ``'machine'``, ``'continuation'`` or ``'empty'``.

    Only ``'user'`` is grounded. Note what is deliberately NOT filtered:
    ``Caveat: The messages below were generated by the user while running local
    commands`` can wrap genuine user text, and slash commands carry their task text
    verbatim, so ``/obi-auto <task>`` grounds normally.
    """
    if not prompt or not prompt.strip():
        return 'empty'

    stripped = prompt.lstrip()
    lowered = stripped.lower()
    for prefix in _MACHINE_PREFIXES:
        if lowered.startswith(prefix):
            return 'machine'

    if _CONTINUATION_RE.match(stripped):
        return 'continuation'

    return 'user'


def _handle(input_data, timer):
    from core.calibration import is_safety_enabled

    # Coerce rather than assume: a non-string `prompt` (seen: an int) would raise
    # in classify_prompt and only be caught by run_hook's catch-all, logging a
    # hook error on every such payload.
    prompt = input_data.get('prompt') or ''
    if not isinstance(prompt, str):
        prompt = str(prompt)
    kind = classify_prompt(prompt)
    # Log the classification and size only. This hook sees every prompt, so
    # logging excerpts would build a standing on-disk record of user input,
    # which can contain credentials.
    timer.set_input_summary(f"kind={kind} chars={len(prompt)}")

    if kind != 'user':
        timer.set_output_summary(f"skipped ({kind})")
        return {}

    # Gate before importing the matcher so a disabled install stays cheap.
    if not is_safety_enabled('auto_inject_sources'):
        timer.set_output_summary("grounding disabled")
        return {}

    from core.pattern_matcher import (
        PatternLoadAborted,
        render_injection,
        select_injections,
    )

    try:
        selected = select_injections(
            prompt,
            deadline_monotonic=time.monotonic() + _GROUNDING_SOFT_BUDGET_SEC,
        )
    except PatternLoadAborted as exc:
        timer.set_output_summary(f"grounding skipped: {exc}")
        return {}
    if not selected:
        timer.set_output_summary("no pattern matched")
        return {}

    from core.calibration import get_max_injected_sources
    from core.session_state import (
        StateUnavailable,
        get_session_state,
        resolve_session_id,
    )

    session_state = get_session_state(resolve_session_id(input_data))
    if session_state is None:
        timer.set_output_summary("no session state")
        return {}

    # Claim the topics and record the session's task type in ONE transaction.
    # Splitting them lets the claim commit while the task_type write fails, and
    # since the topic is then already claimed no later prompt re-enters this path
    # to retry it. Nested calls reuse the outer lock, so this stays one acquisition.
    #
    # session_task_type is the top-ranked MATCH, which is the session's subject
    # even when that topic was grounded on an earlier prompt. It always names a
    # matched pattern, so this never writes 'unknown'.
    session_task_type = selected[0][0]
    claimed = []
    try:
        with session_state.transaction():
            claimed = session_state.claim_topics(
                [topic for topic, _, _ in selected],
                limit=get_max_injected_sources(),
            )
            # Recorded whether or not anything was newly claimed. Gating this on
            # `claimed` would freeze task_type at whatever the last NEW topic was:
            # a session that grounds powershell, then widgetapi, then returns to
            # powershell would keep reporting widgetapi, because the third prompt
            # claims nothing.
            if session_task_type:
                session_state.update(task_type=session_task_type)
    except StateUnavailable:
        timer.set_output_summary("state unavailable — not grounding")
        return {}

    if not claimed:
        timer.set_output_summary("all topics already grounded this session")
        return {}

    injection = render_injection([s for s in selected if s[0] in claimed])
    if not injection:
        # Unreachable given claimed is non-empty and select_injections drops
        # empty-text patterns -- but guard it anyway, because the alternative is
        # rendering the literal "None" into the model's context.
        timer.set_output_summary("nothing to inject")
        return {}

    # Name the topics actually being injected. Using the top MATCH here would
    # announce a topic whose grounding is absent from the block below, whenever
    # that topic was already claimed on an earlier prompt.
    timer.set_output_summary(f"grounded {len(claimed)}: {','.join(claimed)}")
    return {
        "hookSpecificOutput": {
            "hookEventName": "UserPromptSubmit",
            "additionalContext": (
                f"[Obi Memory] Grounding injected for: {', '.join(claimed)}\n"
                f"[Grounding Sources Injected]\n{injection}"
            ),
        }
    }


def main():
    from core.worker_guard import exit_if_worker
    exit_if_worker()  # OPT-23: no-op inside a headless worker subprocess
    from core.hook_runtime import run_hook
    run_hook(
        "UserPromptSubmit",
        _handle,
        error_name="user_prompt_submit",
        fallback={},
    )


if __name__ == '__main__':
    main()
