"""UserPromptSubmit grounding hook (synthetic fixtures).

The hook that finally gives the pattern matcher real text. Its risks are:
injecting off machine-generated prompts, injecting the same block every turn,
leaking prompt text into the execution log, and costing latency on every prompt.
"""

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

HOOKS_DIR = Path(__file__).parent.parent
sys.path.insert(0, str(HOOKS_DIR))

import user_prompt_submit as ups  # noqa: E402
from core.session_state import SessionState  # noqa: E402


class _Timer:
    """Stand-in for HookTimer that records what would be logged."""

    def __init__(self):
        self.input_summary = ''
        self.output_summary = ''

    def set_input_summary(self, text):
        self.input_summary = text

    def set_output_summary(self, text):
        self.output_summary = text


@pytest.fixture
def timer():
    return _Timer()


@pytest.fixture(autouse=True)
def isolated_root(tmp_path, monkeypatch):
    """Point OBI_ROOT at tmp_path so tests never read the real ~/.claude/.obi."""
    monkeypatch.setenv('OBI_ROOT', str(tmp_path))
    return tmp_path


class TestClassifyPrompt:
    """Only genuine user text gets grounded."""

    @pytest.mark.parametrize('prompt', [
        '<task-notification>\n<task-id>abc</task-id>',
        '<system-reminder>do the thing</system-reminder>',
        '<local-command-stdout>widgetapi output</local-command-stdout>',
    ])
    def test_machine_envelopes_are_skipped(self, prompt):
        """Matching keywords against
        machine plumbing would ground constantly and burn the dedupe budget."""
        assert ups.classify_prompt(prompt) == 'machine'

    def test_compaction_continuation_is_skipped(self):
        """A compaction summary names every technology touched all session, so it
        matches many patterns and describes the PAST task."""
        prompt = ('This session is being continued from a previous conversation '
                  'that ran out of context. We worked on WidgetAPI and PowerShell.')
        assert ups.classify_prompt(prompt) == 'continuation'

    @pytest.mark.parametrize('prompt', [
        '<Project><Reference Include="x"/></Project> why does this fail?',
        '<div>foo</div> — should this be a component?',
        'Caveat: The messages below were generated by the user while running '
        'local commands. C:\\> powershell.exe -File build.ps1',
        '/obi-auto fix the widgetapi mail script',
        'update the update set in dev',
    ])
    def test_legitimate_lookalikes_are_user_text(self, prompt):
        """A leading '<' is usually pasted XML/HTML/config — precisely the
        infrastructure text most likely to mention a grounded technology. And
        'Caveat:' envelopes wrap real user text."""
        assert ups.classify_prompt(prompt) == 'user'

    @pytest.mark.parametrize('prompt', ['', '   ', '\n\n'])
    def test_empty(self, prompt):
        assert ups.classify_prompt(prompt) == 'empty'


class TestInjection:
    def test_grounds_a_single_product_mention(self, timer):
        out = ups._handle({'prompt': "let's work on CanvasAPI",
                           'session_id': 's1'}, timer)
        ctx = out['hookSpecificOutput']['additionalContext']
        assert out['hookSpecificOutput']['hookEventName'] == 'UserPromptSubmit'
        # The banner names what was injected, not the session's task type -- they
        # differ once a higher-ranked topic has already been grounded.
        assert 'Grounding injected for: canvasapi' in ctx
        assert '[Grounding Sources Injected]' in ctx

    def test_output_is_json_serializable(self, timer):
        """Claude Code expects exactly one JSON object on stdout."""
        out = ups._handle({'prompt': 'widgetapi update set', 'session_id': 's1'}, timer)
        json.loads(json.dumps(out))

    def test_machine_prompt_injects_nothing(self, timer):
        assert ups._handle({'prompt': '<task-notification>x</task-notification>',
                            'session_id': 's1'}, timer) == {}

    def test_unmatched_prompt_injects_nothing(self, timer):
        assert ups._handle({'prompt': 'what is the weather like',
                            'session_id': 's1'}, timer) == {}

    def test_disabled_by_calibration(self, timer, monkeypatch):
        monkeypatch.setattr('core.calibration.is_safety_enabled', lambda name: False)
        assert ups._handle({'prompt': 'widgetapi update set',
                            'session_id': 's1'}, timer) == {}


class TestDedupe:
    def test_same_topic_grounds_once_per_session(self, timer):
        first = ups._handle({'prompt': 'widgetapi update set', 'session_id': 's1'}, timer)
        second = ups._handle({'prompt': 'another widgetapi business rule',
                              'session_id': 's1'}, timer)
        assert first != {}
        assert second == {}, 'a topic must not be re-injected in the same session'

    def test_a_different_topic_still_grounds(self, timer):
        ups._handle({'prompt': 'widgetapi update set', 'session_id': 's1'}, timer)
        out = ups._handle({'prompt': 'check the storagehost datastore', 'session_id': 's1'}, timer)
        assert 'storageapi' in out['hookSpecificOutput']['additionalContext']

    def test_a_new_session_grounds_again(self, timer):
        ups._handle({'prompt': 'widgetapi update set', 'session_id': 's1'}, timer)
        out = ups._handle({'prompt': 'widgetapi update set', 'session_id': 's2'}, timer)
        assert out != {}

    def test_only_claimed_topics_are_injected(self, timer):
        """If one topic was already claimed, the injected text must contain the
        fresh topic only -- not the one already grounded."""
        ups._handle({'prompt': 'widgetapi update set', 'session_id': 's1'}, timer)
        out = ups._handle({'prompt': 'widgetapi plus powershell pester',
                           'session_id': 's1'}, timer)
        ctx = out['hookSpecificOutput']['additionalContext']
        assert '[Pattern: powershell' in ctx
        assert '[Pattern: widgetapi' not in ctx

    # 'widgetapi update set and pester' ranks widgetapi FIRST (2 anchor hits:
    # widgetapi, update set) with powershell second (1: pester). Claiming
    # widgetapi on an earlier prompt then makes the top-ranked topic the stale
    # one and the fresh topic the lower-ranked one -- the case where the banner
    # and the injected block can disagree.
    _TOP_IS_STALE = 'widgetapi update set and pester'

    def test_banner_names_only_what_it_injected(self, timer):
        """The 'Detected task type' line must not announce a topic whose
        grounding is absent from the block below it."""
        ups._handle({'prompt': 'widgetapi update set', 'session_id': 's1'}, timer)
        out = ups._handle({'prompt': self._TOP_IS_STALE, 'session_id': 's1'}, timer)

        ctx = out['hookSpecificOutput']['additionalContext']
        banner = ctx.splitlines()[0]
        assert 'powershell' in banner, banner
        assert 'widgetapi' not in banner, (
            'banner named the stale top match, not what was injected'
        )
        assert '[Pattern: powershell' in ctx
        assert '[Pattern: widgetapi' not in ctx

    def test_session_task_type_is_the_top_match(self, timer):
        """task_type tracks the session's subject -- the top-ranked match, even
        when that topic was grounded earlier. Deliberately distinct from the
        banner, which names only what this prompt injected."""
        ups._handle({'prompt': 'widgetapi update set', 'session_id': 's1'}, timer)
        ups._handle({'prompt': self._TOP_IS_STALE, 'session_id': 's1'}, timer)
        assert SessionState('s1').get('task_type') == 'widgetapi'


class TestFailClosed:
    def test_no_injection_when_the_claim_cannot_be_recorded(self, timer, monkeypatch):
        """Injecting without recording the claim would repeat the block on every
        later prompt, which is worse than not grounding at all."""
        monkeypatch.setattr(SessionState, 'claim_topics', lambda self, c, limit: [])
        assert ups._handle({'prompt': 'widgetapi update set',
                            'session_id': 's1'}, timer) == {}

    def test_never_raises_when_state_is_unwritable(self, timer, monkeypatch):
        from core.session_state import StateUnavailable

        def boom(self, *a, **k):
            raise StateUnavailable('locked')

        monkeypatch.setattr(SessionState, 'transaction', boom)
        assert ups._handle({'prompt': 'widgetapi update set',
                            'session_id': 's1'}, timer) == {}


class TestTaskTypePersistence:
    def test_task_type_reaches_stop(self, timer):
        """The end-to-end assertion for issue #202: a grounded prompt must make
        Stop report a real task type instead of 'unknown'."""
        from core.stop_pipeline import resolve_task_type

        ups._handle({'prompt': 'widgetapi update set', 'session_id': 's1'}, timer)

        snapshot = SessionState('s1').get_all()
        assert resolve_task_type({}, snapshot) == 'widgetapi'


class TestLoggingSafety:
    """This hook sees EVERY prompt, so any logged excerpt becomes a standing
    on-disk record of user input -- which routinely contains credentials."""

    def test_prompt_text_is_never_logged(self, timer):
        secret = 'synthetic-' + 'Q' * 24
        ups._handle({'prompt': f'widgetapi update set {secret}',
                     'session_id': 's1'}, timer)

        assert secret not in timer.input_summary
        assert secret not in timer.output_summary
        assert 'kind=user' in timer.input_summary
        assert 'chars=' in timer.input_summary

    @pytest.mark.parametrize('mode', ['plain', 'non-string-prompt'])
    def test_secret_reaches_no_real_log_file(self, tmp_path, mode):
        """Run the REAL hook as a subprocess and grep the REAL logs.

        Asserting against a stub timer only proves the handler's intent; it says
        nothing about what run_hook actually persists.

        Neither case errors -- the non-string prompt is coerced rather than
        raising, which is the point of that fix. The genuine error path is
        covered separately below.
        """
        secret = 'synthetic-' + 'R' * 24
        payload = {'prompt': f'widgetapi update set {secret}',
                   'session_id': 'logsafety'}
        if mode == 'non-string-prompt':
            payload['prompt'] = {'nested': secret}

        env = dict(os.environ, OBI_ROOT=str(tmp_path), PYTHONIOENCODING='utf-8')
        proc = subprocess.run(
            [sys.executable, str(HOOKS_DIR / 'user_prompt_submit.py')],
            input=json.dumps(payload), capture_output=True, text=True,
            timeout=120, env=env, cwd=str(HOOKS_DIR),
        )
        assert proc.returncode == 0, proc.stderr

        obi = tmp_path / '.obi'
        scanned = []
        for name in ('hook-execution-log.jsonl', 'hook-errors.jsonl',
                     'swallowed-errors.jsonl'):
            p = obi / name
            if p.exists():
                scanned.append(name)
                assert secret not in p.read_text(encoding='utf-8'), (
                    f'{mode}: prompt text leaked into {name}'
                )
        assert scanned, 'no log files were written -- test proves nothing'

    def test_secret_absent_when_the_handler_actually_raises(self, tmp_path, monkeypatch):
        """The real error path: respond_with_error writes a record, and the
        prompt must not ride along in it."""
        import io

        from core.hook_runtime import run_hook

        monkeypatch.setenv('OBI_ROOT', str(tmp_path))
        secret = 'synthetic-' + 'S' * 24
        monkeypatch.setattr(
            sys, 'stdin',
            io.StringIO(json.dumps({'prompt': f'widgetapi {secret}',
                                    'session_id': 'errpath'})))

        def boom(input_data, timer):
            timer.set_input_summary('kind=user chars=42')
            raise RuntimeError('forced failure for the error path')

        with pytest.raises(SystemExit):
            run_hook('UserPromptSubmit', boom,
                     error_name='user_prompt_submit', fallback={})

        obi = tmp_path / '.obi'
        wrote_something = False
        for p in obi.rglob('*.jsonl'):
            wrote_something = True
            assert secret not in p.read_text(encoding='utf-8'), (
                f'prompt text leaked into {p.name} on the error path'
            )
        assert wrote_something, 'error path wrote no log -- test proves nothing'


class TestManifest:
    def test_hook_is_registered_in_the_manifest(self):
        """healthcheck drives its hook checks off this manifest, so a hook
        missing from it is never smoke-tested."""
        manifest = json.loads(
            (HOOKS_DIR.parent / 'tools' / 'lib' / 'hook-manifest.json').read_text(encoding='utf-8')
        )
        files = [h['file'] for h in manifest['hooks']]
        assert 'user_prompt_submit.py' in files
        assert 'pre_compact.py' in files, 'PreCompact is wired in settings but was absent'
